//
// UserParam.swift
//
// Generated by swagger-codegen
//

import Foundation

public struct UserParam: Codable {
    
    /** ニックネーム */
    public var nickname: String?
    
    /** メールアドレス */
    public var email: String?
    
    public init(nickname: String?, email: String?) {
        self.nickname = nickname
        self.email = email
    }
    
    public enum CodingKeys: String, CodingKey {
        case nickname
        case email
    }
}
