//
// User.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct User: Codable {

    public enum Gender: String, Codable { 
        case unknown = "unknown"
        case male = "male"
        case female = "female"
        case other = "other"
        
        static let allValues = [unknown, male, female, other]
    }

    /** ニックネーム */
    public var nickname: String

    /** 生年月日 */
    //public var birthday: String?
    /** 性別 */
    //public var gender: Gender?

    /** メールアドレス */
    public var email: String?

    /** パスワード */
    public var password: String?

    public init(nickname: String, /*birthday: String?, gender: Gender?,*/ email: String?, password: String?) {
        self.nickname = nickname
        self.email = email
        self.password = password
    }

    public enum CodingKeys: String, CodingKey { 
        case nickname
        case email
        case password = "password"
    }
}

